name: Deploy Sample

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: sample-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-sample:
    environment: sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: sudo apt install libcairo2-dev pkg-config python3-dev ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Update lockfile
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ADT Press
        run: |
          uv run adt-press.py pdf_path=./assets/raven.pdf label=raven
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload sample artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-${{ github.run_id }}
          path: output/raven/

  push-azure:
    needs: build-sample
    environment: sample
    runs-on: ubuntu-latest
    steps:          
      - name: Download sample artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-${{ github.run_id }}
          path: output/raven/

      - name: Install azcopy
        run: sudo apt install azcopy    

      - name: Upload to blob storage
        run: |
            azcopy remove 'https://adtpress.blob.core.windows.net/$web/sample?${{ secrets.AZURE_STORAGE_SAS_TOKEN }}' --recursive || true
            azcopy copy 'output/raven/*' 'https://adtpress.blob.core.windows.net/$web/sample/?${{ secrets.AZURE_STORAGE_SAS_TOKEN }}' --recursive --overwrite=true